language: python

matrix:
  include:
  - python: "2.6"
    before_install: nvm i 6
  - python: "2.6"
    before_install: nvm i 7
  - python: "2.6"
    before_install: nvm i 8

  - python: "2.7"
    before_install: nvm i 6
  - python: "2.7"
    before_install: nvm i 7
  - python: "2.7"
    before_install: nvm i 8

  - python: "3.3"
    before_install: nvm i 6
  - python: "3.3"
    before_install: nvm i 7
  - python: "3.3"
    before_install: nvm i 8

  - python: "3.4"
    before_install: nvm i 6
  - python: "3.4"
    before_install: nvm i 7
  - python: "3.4"
    before_install: nvm i 8

  - python: "3.5"
    before_install: nvm i 6
  - python: "3.5"
    before_install: nvm i 7
  - python: "3.5"
    before_install: nvm i 8

  - python: "3.6"
    before_install: nvm i 6
  - python: "3.6"
    before_install: nvm i 7
  - python: "3.6"
    before_install: nvm i 8

  - python: "2.6"
    before_install: nvm i 6
    os: osx
  - python: "2.6"
    before_install: nvm i 7
    os: osx
  - python: "2.6"
    before_install: nvm i 8
    os: osx

  - python: "2.7"
    before_install: nvm i 6
    os: osx
  - python: "2.7"
    before_install: nvm i 7
    os: osx
  - python: "2.7"
    before_install: nvm i 8
    os: osx

  - python: "3.3"
    before_install: nvm i 6
    os: osx
  - python: "3.3"
    before_install: nvm i 7
    os: osx
  - python: "3.3"
    before_install: nvm i 8
    os: osx

  - python: "3.4"
    before_install: nvm i 6
    os: osx
  - python: "3.4"
    before_install: nvm i 7
    os: osx
  - python: "3.4"
    before_install: nvm i 8
    os: osx

  - python: "3.5"
    before_install: nvm i 6
    os: osx
  - python: "3.5"
    before_install: nvm i 7
    os: osx
  - python: "3.5"
    before_install: nvm i 8
    os: osx

  - python: "3.6"
    before_install: nvm i 6
    os: osx
  - python: "3.6"
    before_install: nvm i 7
    os: osx
  - python: "3.6"
    before_install: nvm i 8
    os: osx

os: linux
install: npm i