language: node_js

matrix:
  include:
  - node_js: '6'
    env: PYTHON_VERSION=2.6
    install: npm i --python_version=2.6
  - node_js: '7'
    env:  PYTHON_VERSION=2.6
    install: npm i --python_version=2.6
  - node_js: '8'
    env: PYTHON_VERSION=2.6
    install: npm i --python_version=2.6

  - node_js: '6'
    env: PYTHON_VERSION=2.7
    install: npm i --python_version=2.7
  - node_js: '7'
    env:  PYTHON_VERSION=2.7
    install: npm i --python_version=2.7
  - node_js: '8'
    env: PYTHON_VERSION=2.7
    install: npm i --python_version=2.7

  - node_js: '6'
    env: PYTHON_VERSION=3.3
    install: npm i --python_version=3.3
  - node_js: '7'
    env:  PYTHON_VERSION=3.3
    install: npm i --python_version=3.3
  - node_js: '8'
    env: PYTHON_VERSION=3.3
    install: npm i --python_version=3.3

  - node_js: '6'
    env: PYTHON_VERSION=3.4
    install: npm i --python_version=3.4
  - node_js: '7'
    env:  PYTHON_VERSION=3.4
    install: npm i --python_version=3.4
  - node_js: '8'
    env: PYTHON_VERSION=3.4
    install: npm i --python_version=3.4

  - node_js: '6'
    env: PYTHON_VERSION=3.5
    install: npm i --python_version=3.5
  - node_js: '7'
    env:  PYTHON_VERSION=3.5
    install: npm i --python_version=3.5
  - node_js: '8'
    env: PYTHON_VERSION=3.5
    install: npm i --python_version=3.5

  - node_js: '6'
    env: PYTHON_VERSION=3.6
    install: npm i --python_version=3.6
  - node_js: '7'
    env:  PYTHON_VERSION=3.6
    install: npm i --python_version=3.6
  - node_js: '8'
    env: PYTHON_VERSION=3.6
    install: npm i --python_version=3.6

  - env:
    - NODE_VERSION=6
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js
  - env:
    - NODE_VERSION=7
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js
  - env:
    - NODE_VERSION=8
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js

  - env:
    - NODE_VERSION=6
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js
  - env:
    - NODE_VERSION=7
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js
  - env:
    - NODE_VERSION=8
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js

os: linux
install: npm i
script: npm test
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python$PYTHON_VERSION python$PYTHON_VERSION-dev