language: node_js

matrix:
  include:
  - node_js: '6'
    env: PYTHON_VERSION=2.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.6 python2.6-dev
  - node_js: '7'
    env:  PYTHON_VERSION=2.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.6 python2.6-dev
  - node_js: '8'
    env: PYTHON_VERSION=2.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.6 python2.6-dev

  - node_js: '6'
    env: PYTHON_VERSION=2.7
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.7 python2.7-dev
  - node_js: '7'
    env:  PYTHON_VERSION=2.7
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.7 python2.7-dev
  - node_js: '8'
    env: PYTHON_VERSION=2.7
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.7 python2.7-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.3
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.3 python3.3-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.3
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.3 python3.3-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.3
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.3 python3.3-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.4
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.4 python3.4-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.4
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.4 python3.4-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.4
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.4 python3.4-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.5
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.5 python3.5-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.5
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.5 python3.5-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.5
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.5 python3.5-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-dev

  - env:
    - NODE_VERSION=6
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js
  - env:
    - NODE_VERSION=7
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js
  - env:
    - NODE_VERSION=8
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js

  - env:
    - NODE_VERSION=6
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js
  - env:
    - NODE_VERSION=7
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js
  - env:
    - NODE_VERSION=8
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js

os: linux
install: npm i --python_version=$PYTHON_VERSION
script: npm test
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python$PYTHON_VERSION python$PYTHON_VERSION-dev