language: python

matrix:
  include:
  - python: "2.6"
    env: NODE_VERSION=6
    install: npm i --python_version=2.6
  - python: "2.6"
    env: NODE_VERSION=7
    install: npm i --python_version=2.6
  - python: "2.6"
    env: NODE_VERSION=8
    install: npm i --python_version=2.6

  - python: "2.7"
    env: NODE_VERSION=6
    install: npm i --python_version=2.7
  - python: "2.7"
    env: NODE_VERSION=7
    install: npm i --python_version=2.7
  - python: "2.7"
    env: NODE_VERSION=8
    install: npm i --python_version=2.7

  - python: "3.3"
    env: NODE_VERSION=6
    install: npm i --python_version=3.3
  - python: "3.3"
    env: NODE_VERSION=7
    install: npm i --python_version=3.3
  - python: "3.3"
    env: NODE_VERSION=8
    install: npm i --python_version=3.3

  - python: "3.4"
    env: NODE_VERSION=6
    install: npm i --python_version=3.4
  - python: "3.4"
    env: NODE_VERSION=7
    install: npm i --python_version=3.4
  - python: "3.4"
    env: NODE_VERSION=8
    install: npm i --python_version=3.4

  - python: "3.5.3"
    env: 
    - NODE_VERSION=6
    - LD_RUN_PATH=/opt/python/3.5.3/lib
    install: npm i --python_version=3.5
  - python: "3.5.3"
    env: 
    - NODE_VERSION=7
    - LD_RUN_PATH=/opt/python/3.5.3/lib
    install: npm i --python_version=3.5
  - python: "3.5.3"
    env: 
    - NODE_VERSION=8
    - LD_RUN_PATH=/opt/python/3.5.3/lib
    install: npm i --python_version=3.5

  - env: 
    - NODE_VERSION=6
    install: npm i --python_version=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-config
  - env: 
    - NODE_VERSION=7
    install: npm i --python_version=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-config
  - env: 
    - NODE_VERSION=8
    install: npm i --python_version=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-config

  - env:
    - NODE_VERSION=6
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js
  - env:
    - NODE_VERSION=7
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js
  - env:
    - NODE_VERSION=8
    - PYTHON_VERSION=2
    os: osx
    install: npm i --python_version=2
    language: node_js

  - env:
    - NODE_VERSION=6
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js
  - env:
    - NODE_VERSION=7
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js
  - env:
    - NODE_VERSION=8
    - PYTHON_VERSION=3
    os: osx
    install: 
    - brew install python3
    - npm i --python_version=3
    language: node_js

os: linux
before_install: nvm i $NODE_VERSION
install: npm i
script: npm test