language: node_js

matrix:
  include:
  - node_js: '6'
    env: PYTHON_VERSION=2.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.6 python2.6-dev
  - node_js: '7'
    env:  PYTHON_VERSION=2.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.6 python2.6-dev
  - node_js: '8'
    env: PYTHON_VERSION=2.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.6 python2.6-dev

  - node_js: '6'
    env: PYTHON_VERSION=2.7
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.7 python2.7-dev
  - node_js: '7'
    env:  PYTHON_VERSION=2.7
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.7 python2.7-dev
  - node_js: '8'
    env: PYTHON_VERSION=2.7
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python2.7 python2.7-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.3
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.3 python3.3-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.3
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.3 python3.3-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.3
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.3 python3.3-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.4
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.4 python3.4-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.4
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.4 python3.4-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.4
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.4 python3.4-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.5
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.5 python3.5-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.5
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.5 python3.5-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.5
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.5 python3.5-dev

  - node_js: '6'
    env: PYTHON_VERSION=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-dev
  - node_js: '7'
    env:  PYTHON_VERSION=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-dev
  - node_js: '8'
    env: PYTHON_VERSION=3.6
    addons:
      apt:
        sources:
        - deadsnakes
        packages:
        - python3.6 python3.6-dev

  - node_js: '6'
    env: PYTHON_VERSION=2
    os: osx
  - node_js: '7'
    env: PYTHON_VERSION=2
    os: osx
  - node_js: '8'
    env: PYTHON_VERSION=2
    os: osx

  - node_js: '6'
    env: PYTHON_VERSION=3
    os: osx
    before_install: brew install python3
  - node_js: '7'
    env: PYTHON_VERSION=3
    os: osx
    before_install: brew install python3
  - node_js: '8'
    env: PYTHON_VERSION=3
    os: osx
    before_install: brew install python3

os: linux
install: npm i --python_version=$PYTHON_VERSION
script: npm test