language: node_js
node_js: 
  - "8"
  - "7"
  - "6"
os:
  - linux
  - osx
env:
  - LD_RUN_PATH=/opt/python/3.5.3/lib
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi