environment:
  matrix:
    - PYTHON: "C:\\Python26-x64"
      nodejs_version: "8"
    - PYTHON: "C:\\Python27-x64"
      nodejs_version: "8"
    - PYTHON: "C:\\Python33-x64"
      nodejs_version: "8"
    - PYTHON: "C:\\Python34-x64"
      nodejs_version: "8"
    - PYTHON: "C:\\Python35-x64"
      nodejs_version: "8"
    - PYTHON: "C:\\Python36-x64"
      nodejs_version: "8"

    - PYTHON: "C:\\Python26-x64"
      nodejs_version: "7"
    - PYTHON: "C:\\Python27-x64"
      nodejs_version: "7"
    - PYTHON: "C:\\Python33-x64"
      nodejs_version: "7"
    - PYTHON: "C:\\Python34-x64"
      nodejs_version: "7"
    - PYTHON: "C:\\Python35-x64"
      nodejs_version: "7"
    - PYTHON: "C:\\Python36-x64"
      nodejs_version: "7"

    - PYTHON: "C:\\Python26-x64"
      nodejs_version: "6"
    - PYTHON: "C:\\Python27-x64"
      nodejs_version: "6"
    - PYTHON: "C:\\Python33-x64"
      nodejs_version: "6"
    - PYTHON: "C:\\Python34-x64"
      nodejs_version: "6"
    - PYTHON: "C:\\Python35-x64"
      nodejs_version: "6"
    - PYTHON: "C:\\Python36-x64"
      nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Prepend Python 3 to the PATH of this build 
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - npm install 

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - python --version
  - node --version
  - npm --version
  # Test
  - npm test

# Don't actually build.
build: off